Update Package Generator for NIM.
ckeditor/ckeditor5-package-generator pull request #166
Opened 2024-04-26 13:35 UTC by pszczesniak

### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Other (scope): Message. Closes https://github.com/cksource/ckeditor5-commercial/issues/6190.

BREAKING CHANGE: TODO...

---

### Additional information

*For example – encountered issues, assumptions you had to make, other affected tickets, etc.*

### Supported scopes

* `generator` → https://www.npmjs.com/package/ckeditor5-package-generator
* `*` → https://www.npmjs.com/package/@ckeditor/ckeditor5-package-*

2024-05-16 09:57 UTC, filipsobol approved these changes

2024-05-21 14:35 UTC, przemyslaw-zan requested changes
The `build:dist` script in non-legacy TS package using yarn shows some kind of warning:

```
$ yarn run  build:dist
yarn run v1.22.19
$ node ./scripts/build-dist.mjs
1/2: Generating NPM build...
2/2: Generating browser build...
No name was provided for external module "ckeditor5" in "output.globals" – guessing "ckeditor5".
Done in 5.36s.
```

Other than that, everything seems to work properly.

2024-05-22 10:01 UTC, pszczesniak commented on packages/ckeditor5-package-generator/lib/templates/ts/tsconfig.dist.json
> +/**
Will remove it from here and will mention about it in docs for `package-generator` and in migration guide.

2024-05-22 10:50 UTC, pszczesniak commented on packages/ckeditor5-package-generator/lib/utils/copy-files.js
> +		.replace( /^(?:common|js|ts|legacy-js|legacy-ts)(?:\\|\/)/, '' )
Fully agree. Addressed in 9b05427

2024-05-22 11:08 UTC, pszczesniak commented
> The `build:dist` script in non-legacy TS package using yarn shows some kind of warning:

Yes, it's on out todo list to fix in `ckeditor5-dev-build-tools` it will be done till the `CKEditor5` release with NIM.

2024-05-24 15:27 UTC, przemyslaw-zan approved these changes
LGTM 👍

2024-05-27 14:27 UTC, przemyslaw-zan requested changes
I think we should rename the cli option, to something like:
`--without-legacy-methods` => `--use-new-installation-methods`

2024-05-28 07:27 UTC, pszczesniak commented
@przemyslaw-zan we decided to name the flag `--use-only-new-installation-methods` to make it more explicit.

2024-05-28 10:39 UTC, pomek commented
Changes from this branch have been released: https://github.com/ckeditor/ckeditor5-package-generator/releases/tag/v2.0.0-alpha.0.

2024-06-24 08:53 UTC, merged